### ISSUE TITLE
Impliment auto-manual switch

### ISSUE THREAD

**Issue by andyblarblar** [iscumd/Ohm#13]
We currently do not have a physical automatic/manual drive mode selection switch. Electrical added the physical switch, but there is no logic currently.

Currently, the only way we swap to automatic is via pressing start on a connected controller. When it does this, we immediatly swap to automatic with no warning.

In the intrest of safety, we should use the physical switch as a kind of enable switch, which will enter manual if in manual, or _allow_ switching to automatic using the controller if set to auto. 

This will make it so that the only way the nuc can be in automatic is if the ardunio says so. This ensures that our state machine must be followed if killed ect, and allows the ardunio to force the robot to alert its surroundings of its inpending movement before entering auto. (makes for a great bragging point if we present at the compition as well).

# Proposed logic 
1. Joystick start is pressed, causing a message of 'A' or 'M' to be sent to the arduino, whichever is the opposite state from the one we're in.
2. Arduino checks this msg. If M, then always enter M. If A, then enter A iff the switch is in the auto position.
2.1. If entering A, then wait for 5 seconds and sound the buzzer(?) before actually setting A to allow for people to be alerted.
3. In every msg to the nuc, report A or M via 1 or 0 in the first digit of the msg. This is currently the estopstate, which is redundant as we already track killed.
4. On every read from the ardunio, publish `state::AUTOMATIC` or `state::MANUAL` on topic "drive_mode" as recived from the arduino.
5. This topic is subscribed to by the `robot_state_machine` and `goal_selection`. The state machine will simply change its state to match the topic. Goal selection will only attempt to use the nav stack to approch a waypoint if the state is A.

## Arduino 
1. The ardunio must track changes to this switch, and change to M if swapped down.
2. We need to make sure that the arduino and nuc never lose sync if for example, the 22v goes down, killing only the arduino. This may be already working.

# TODO
- [ ] Add arduino wait and buzz safety function.
- [ ] Add arduino logic for changing A->M and M->A as detailed above and change msg to send A or M as 1 or 0 in the first digit.
- [ ] Remove or change the joystick handling in `drive_mode_switch` to send a msg to the arduino instead of setting the state right away.  To send to the ardunio, we could set up a service in the arduino_comm node that sends a state sent over the service when called with a next state, then call this service in the switch node.
- [ ] Change the logic in `ardunio_comm` to handle the first index of the message read to be interprited as the current state, not the estopstate as it is now. Next publish this state on the "drive_mode" topic in the publish_arduino_state function.
