### ISSUE TITLE
Break out flir camera to it's own node 

### ISSUE THREAD

**Issue by andyblarblar** [iscumd/Ohm#20]
The white_line_detection node currently hard codes the flir camera into the node. In order to use this node with gazebo, we need to convert the white line detection node to work on ros image streams. This involves adding a flir driver node to publish the image stream.

The white line detections node currently uses globals to pass between functions. We should refactor this to use arguments and returns in functions like a normal program. This is neccisary to extract the current while loop in main into a function we can use as a callback to the ros topic subscription. This should convert the node to publish white line pointclouds whenever an image is published, rather than driving the publishing itself. This means white_line_detection should not error if there is no camera, and will simply do nothing.

# TODO

- [x] Refactor white line detection to use ros topics instead of the camera
- [ ] Test with gazebo
- [ ]  Find a flir node for comp

**Comment by andyblarblar** [comment]
Refactored the node as described. It currently fails to compile due to an issue including cv_bridge, but should work. Just needs a little more documentation and the changes to the node will be done.

**Comment by andyblarblar** [comment]
Just needed to add cv_bridge as a dep. The node refactor should be done, and will open a PR for that component. I will leave this issue open as we still need to add the flir driver.

**Comment by andyblarblar** [comment]
PR is #21
